---
slug: "early"
output: 
  html_document:
    css: "calendar.css"
showonlyimage: true
description: " "
type: packagecalendar
layout:: single
---

<html>
    <link rel="stylesheet" href="calendar-post.css"/>
</html>

```{r setup, include=FALSE}
library(knitr)
library(htmltools)
opts_chunk$set(
  echo = TRUE, 
  cache = TRUE,
  collapse = TRUE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618, # 1 / phi
  out.width = "700px")
knit_hooks$set(optipng = hook_optipng)
opts_chunk$set("optipng" = "-o5")
```

```{r, echo=FALSE}
tags$section(class = "navigation",
  tags$div(class = "nav-container",
    tags$nav(
      tags$ul(class = "nav-list",
        tags$li(
          tags$a(href = "/", "Home")
        ),
        tags$li(
          tags$a(href = "/packagecalendar/2019/", "Back")
        )
      )
    )
  )
)
```

# Somebody (you) have to wait a little longer ;)

You came a little early for this post. Please come back again.

```{r, eval=FALSE}
notice <- function("nice") {syntax highlighting + 1}
```

